import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ContactPopup from "@/components/ContactPopup";
import I18nProvider from "@/components/I18nProvider";
import LanguageSwitcher from "@/components/LanguageSwitcher";
import ScrollToTop from "@/components/ScrollToTop";
import ClientOnly from "@/components/ClientOnly";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} relative antialiased min-h-screen flex flex-col bg-slate-50 text-black`}
      >
        <I18nProvider>
          <ClientOnly>
            <Navbar />
          </ClientOnly>
          <main className="relative flex flex-col flex-1">
            {children}
            <ClientOnly>
              <ContactPopup />
            </ClientOnly>
            <ClientOnly>
              <LanguageSwitcher />
            </ClientOnly>
            <ScrollToTop />
          </main>
          <ClientOnly>
            <Footer />
          </ClientOnly>
        </I18nProvider>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
